version: "3"
services:
  user-management-project:
    container_name: User-Management-Project
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /user-management-project
    volumes:
      - .:/user-management-project
    ports:
      - 8084:8080
    # network_mode: host
    networks:
      my-net:
        ipv4_address: 172.31.1.2
    # command: ./start.sh
    depends_on:
      - database
  database:
    #image: postgres
    build:
      context: .
      dockerfile: Dockerfile-db
    restart: always
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5436:5432"
    # volumes:
    #   - data:/var/lib/postgresql/data
    networks:
      my-net:
        ipv4_address: 172.31.1.3
  # postgis:
  #   image: cmihai/postgis
  #   restart: always
  #   env_file:
  #     - .env
  #   environment:
  #     PGDATA: /var/lib/postgresql/data
  #   ports:
  #     - "5435:5432"
  #   # volumes:
  #   #   - data:/var/lib/postgresql/data
  #   networks:
  #     my-net:
  #       ipv4_address: 172.26.1.3  

networks:
 my-net:
  ipam:
   driver: default
   config:
    - subnet: 172.31.0.0/16

# volumes:
#   data: