// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"github.com/google/wire"
	"gorm.io/gorm"
	"hendralijaya/user-management-project/controller"
	"hendralijaya/user-management-project/middleware"
	"hendralijaya/user-management-project/repository"
	"hendralijaya/user-management-project/service"
)

// Injectors from injector.go:

func InitUser(db *gorm.DB) controller.UserController {
	userRepository := repository.NewUserRepository(db)
	userService := service.NewUserService(userRepository)
	jwtService := service.NewJWTService()
	userController := controller.NewUserController(userService, jwtService)
	return userController
}

func InitAuth(db *gorm.DB) controller.AuthController {
	userRepository := repository.NewUserRepository(db)
	userService := service.NewUserService(userRepository)
	jwtService := service.NewJWTService()
	authController := controller.NewAuthController(userService, jwtService)
	return authController
}

func InitJWTMiddleware() middleware.AuthorizeJWTMiddleware {
	jwtService := service.NewJWTService()
	authorizeJWTMiddleware := middleware.NewAuthorizeJWTMiddleware(jwtService)
	return authorizeJWTMiddleware
}

func InitAdminMiddleware(db *gorm.DB) middleware.IsAdminMiddleware {
	jwtService := service.NewJWTService()
	userRepository := repository.NewUserRepository(db)
	userService := service.NewUserService(userRepository)
	isAdminMiddleware := middleware.NewIsAdminMiddleware(jwtService, userService)
	return isAdminMiddleware
}

// injector.go:

var jwtMiddlewareSet = wire.NewSet(service.NewJWTService, middleware.NewAuthorizeJWTMiddleware)

var adminMiddlewareSet = wire.NewSet(repository.NewUserRepository, service.NewJWTService, service.NewUserService, middleware.NewIsAdminMiddleware)

var userSet = wire.NewSet(repository.NewUserRepository, service.NewUserService, service.NewJWTService, controller.NewUserController)

var authSet = wire.NewSet(repository.NewUserRepository, service.NewUserService, service.NewJWTService, controller.NewAuthController)
