// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"github.com/google/wire"
	"github.com/sirupsen/logrus"
	"gorm.io/gorm"
	"hendralijaya/user-management-project/controller"
	"hendralijaya/user-management-project/helper"
	"hendralijaya/user-management-project/middleware"
	"hendralijaya/user-management-project/repository"
	"hendralijaya/user-management-project/service"
)

// Injectors from injector.go:

func InitRole(db *gorm.DB) controller.RoleController {
	roleRepository := repository.NewRoleRepository(db)
	roleService := service.NewRoleService(roleRepository)
	jwtService := service.NewJWTService()
	logger := logrus.New()
	log := helper.NewLog(logger)
	roleController := controller.NewRoleController(roleService, jwtService, log)
	return roleController
}

func InitUser(db *gorm.DB) controller.UserController {
	userRepository := repository.NewUserRepository(db)
	userService := service.NewUserService(userRepository)
	jwtService := service.NewJWTService()
	logger := logrus.New()
	log := helper.NewLog(logger)
	userController := controller.NewUserController(userService, jwtService, log)
	return userController
}

func InitAuth(db *gorm.DB) controller.AuthController {
	userRepository := repository.NewUserRepository(db)
	authService := service.NewAuthService(userRepository)
	userService := service.NewUserService(userRepository)
	jwtService := service.NewJWTService()
	logger := logrus.New()
	log := helper.NewLog(logger)
	authController := controller.NewAuthController(authService, userService, jwtService, log)
	return authController
}

func InitJWTMiddleware() middleware.AuthorizeJWTMiddleware {
	jwtService := service.NewJWTService()
	authorizeJWTMiddleware := middleware.NewAuthorizeJWTMiddleware(jwtService)
	return authorizeJWTMiddleware
}

func InitAdminMiddleware(db *gorm.DB) middleware.IsAdminMiddleware {
	jwtService := service.NewJWTService()
	userRepository := repository.NewUserRepository(db)
	userService := service.NewUserService(userRepository)
	logger := logrus.New()
	log := helper.NewLog(logger)
	isAdminMiddleware := middleware.NewIsAdminMiddleware(jwtService, userService, log)
	return isAdminMiddleware
}

// injector.go:

var jwtMiddlewareSet = wire.NewSet(service.NewJWTService, middleware.NewAuthorizeJWTMiddleware)

var adminMiddlewareSet = wire.NewSet(logrus.New, helper.NewLog, repository.NewUserRepository, service.NewJWTService, service.NewUserService, middleware.NewIsAdminMiddleware)

var roleSet = wire.NewSet(logrus.New, helper.NewLog, repository.NewRoleRepository, service.NewRoleService, service.NewJWTService, controller.NewRoleController)

var userSet = wire.NewSet(logrus.New, helper.NewLog, repository.NewUserRepository, service.NewUserService, service.NewJWTService, controller.NewUserController)

var authSet = wire.NewSet(logrus.New, helper.NewLog, repository.NewUserRepository, service.NewAuthService, service.NewUserService, service.NewJWTService, controller.NewAuthController)
